language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Install dependencies
  - gem install sass
  - sudo apt-get install pandoc less yui-compressor
  - sudo npm -g install myth roy coffee-script

script:
  - cl -e '(ql:quickload :fiveam)'
       -e '(setf fiveam:*debug-on-error* t
                 fiveam:*debug-on-failure* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :asdf-linguist-test)'

notifications:
  email:
    - eudoxiahp@gmail.com
